module.exports = {
  purge: {
    content: ["./src/**/*.js", "./src/**/*.jsx", "./src/**/*.ts", "./src/**/*.tsx"],
    safelist: [
      'flex-row',
      'flex-row-reverse',
      'flex-col',
      'flex-col-reverse',
      'flex-wrap',
      'flex-wrap-reverse',
      'flex-nowrap',
      'grid-cols-1',
      'grid-cols-2',
      'grid-cols-3',
      'grid-cols-4',
      'grid-cols-5',
      'grid-rows-1',
      'grid-rows-2',
      'grid-rows-3',
      'grid-rows-4',
      'grid-rows-5',
      'grid-flow-row',
      'grid-flow-col',
      'grid-flow-row-dense',
      'grid-flow-col-dense',
      'gap-1',
      'gap-2',
      'gap-3',
      'gap-4',
      'gap-5',
      'font-weight: 700',
      'h6',
      'h5',
      'h4',
      'h3',
      'h2',
      'h1',
      'text-left',
      'text-center',
      'text-right',
      'text-justify',
      'text-xs',
      'text-sm',
      'text-base',
      'text-lg',
      'text-xl',
      'text-2xl',
      'text-4xl',
    ]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    fontFamily: {
      sans: "Roboto, Arial, sans-serif",
      serif: "Merriweather, Georgia, serif",
    },
    extend: {
      colors: {
        primary: "#672E9B",
        gray: {
          300: "#f0f0f0",
        },
      },
    },
    fontSize: {
      xs: [".5rem",".6rem"],
      sm: [".75rem",".85rem"],
      tiny: [".85rem","1rem"],
      base: ["1rem","1.125rem"],
      lg: ["1.125rem","1.25rem"],
      xl: ["1.25rem","1.5rem"],
      "2xl": ["1.5rem","1.875rem"],
      "3xl": ["1.875rem","2rem"],
      "4xl": ["2.25rem","2.5rem"],
    },
    maxWidth: {
      '10p': '10%',
      '20p': '20%',
      '30p': '30%',
      '40p': '40%',
      '50p': '50%',
      '60p': '60%',
      '70p': '70%',
      '80p': '80%',
      '90p': '90%',
      '100p': '100%',
     },
     lineHeight: {
      'leading-3': '0.6rem',
      '3': '0.6rem',
      'leading-4': '0.75rem',
      '4': '0.75rem',
      'leading-5': '1rem',
      '5': '1rem',
      'leading-6': '1.25rem',
      '6': '1.25rem',
      'leading-7': '1.5rem',
      '7': '1.5rem',
    }
  },
  variants: {},
  plugins: [],
}
