module.exports = {
  purge: {
    content: ["./src/**/*.js", "./src/**/*.jsx", "./src/**/*.ts", "./src/**/*.tsx"],
    safelist: [
      'flex-row',
      'flex-row-reverse',
      'flex-col',
      'flex-col-reverse',
      'flex-wrap',
      'flex-wrap-reverse',
      'flex-nowrap',
      'grid-cols-1',
      'grid-cols-2',
      'grid-cols-3',
      'grid-cols-4',
      'grid-cols-5',
      'grid-rows-1',
      'grid-rows-2',
      'grid-rows-3',
      'grid-rows-4',
      'grid-rows-5',
      'grid-flow-row',
      'grid-flow-col',
      'grid-flow-row-dense',
      'grid-flow-col-dense',
      'gap-1',
      'gap-2',
      'gap-3',
      'gap-4',
      'gap-5',
      'font-weight: 700',
      'h5',
      'h4',
      'h3',
      'h2',
      'h1',
      'text-left',
      'text-center',
      'text-right',
      'text-justify',
      'text-xs',
      'text-sm',
      'text-base',
      'text-lg',
      'text-xl',
      'text-2xl',
      'text-4xl',
    ]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    fontFamily: {
      sans: "Roboto, Arial, sans-serif",
      serif: "Merriweather, Georgia, serif",
    },
    extend: {
      colors: {
        primary: "#672E9B",
        gray: {
          300: "#f0f0f0",
        },
      },
    },
    fontSize: {
      xs: ".5rem",
      sm: ".75rem",
      tiny: ".85rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": ["2.25rem","2.5rem"],
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    maxWidth: {
      '10p': '10%',
      '20p': '20%',
      '30p': '30%',
      '40p': '40%',
      '50p': '50%',
      '60p': '60%',
      '70p': '70%',
      '80p': '80%',
      '90p': '90%',
      '100p': '100%',
     },
  },
  variants: {},
  plugins: [],
}
